server:
  port: 8080
  servlet:
    context-path: /
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: NMtvFLJKxn28JUAq4FsBPk8ZoY1IN00S
            client-secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://dev-123456.us.auth0.com/

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG